<?php
/**
 * Created by 高远
 * Date: 2016/11/3
 * Time: 14:07
 */

namespace app\index\controller;


use app\index\model\Message;
use app\index\model\Ucenter;
use think\Request;

class Account extends  Base
{


    public  function _initialize()
    {


        parent::_initialize(); // TODO: Change the autogenerated stub

    }
    public  function  index(){

        $userInfo=session('user');
        $message_action['to'] =  $userInfo['id'];


        $message_action['stage_id'] =  array('neq', 0);

        $messageM   =  new  Message();

        $message_stage_result  =   $messageM->getlist($message_action);

        unset($message_action['stage_id']);
        $message_action['stage_id'] =  array('eq', 0);
        $message_project_result  =   $messageM->getlist1($message_action);



        $this->assign('messagestageLog',$message_stage_result);
        $this->assign('messageproLog',$message_project_result);
            return $this->fetch();

    }

    //修改密码
    public  function changePW(){


        $request    =    Request::instance();

        $list       =   $request->param();

        $ucenterM   =   new Ucenter();
        $result     =   $ucenterM  ->changePw($list);

        return $result;
    }



}