<?php
/**
 * Created by 高远
 * Date: 2016/11/4
 * Time: 15:23
 */

namespace app\index\controller;


use think\Request;

class Event extends Base
{
    public function _initialize()
    {


        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function newEvent()
    {
        $eventM = new \app\index\model\Event();
        $request = Request::instance();
        $list = $request->param();
        $userInfo = session('user');
        $list['ucenter_id'] = $userInfo['id'];
        $list['event_time']=strtotime($list['event_time']);


        $result = $eventM->newEvent($list);
        return $result;


    }

    //删除事件
    public function deleteEvent()
    {
        $request = Request::instance();
        $list = $request->param();
        $eventM = new \app\index\model\Event();
        $a = implode(',', $list['id']);

        $b['id'] = array('in', $a);
        $result = $eventM->deleteEvent($b);
        return $result;


    }

    //编辑事件
    public function editEvent()
    {

        $request = Request::instance();
        $list = $request->param();
        $eventM = new \app\index\model\Event();
$list['event_time']=strtotime($list['event_time']);

        $result = $eventM->editEvent($list);

        return $result;

    }


}