<?php
/**
 * Created by 高远
 * Date: 2016/10/25
 * Time: 15:48
 */

namespace app\index\controller;


use app\index\model\FileShare;
use think\Controller;
use think\Request;

class File extends Controller
{
    public function _initialize()
    {


        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function image()
    {
        $fileM = new \app\index\model\File();
        $result = $fileM->uploadImage();
        return $result;

    }


    //上传
    public function upload()
    {
        $file = request()->file('file');

        //项目的id
        $project_id = input('id');
        $folder_id = input('folder_id');
        if ($folder_id == "" || $folder_id == null) {
            $folder_id = 0;

        }


        if ($file) {

            // 移动到框架应用根目录/public/uploads/ 目录下
            $info = $file->move(ROOT_PATH.'public'.DS .'uploads','', false);

            if ($info) {
                // 成功上传后 获取上传信息
                $fileM = new \app\index\model\File();
                $data['project_id'] = $project_id;
                $data['name'] = $info->getInfo('name');
                $data['mime'] = $info->getInfo('type');
                $data['size'] = $info->getInfo('size');
                $data['folder_id'] = $folder_id;
                $data['ext'] = $info->getExtension();
                $data['save_name'] = $info->getFilename();
//                $data['save_name']  =   $info->getInfo('name');
                $data['save_path'] = $info->getSaveName();
//                $path = dirname(dirname(dirname(dirname(__FILE__)))) . '/public';;
//                $path = str_replace('\\', '/', $path);
//                $data['save_path'] = str_replace($path, '', $data['save_path']);
                $data['save_path'] = '/public/uploads/' . $data['save_path'];
                $data['save_path'] = str_replace('\\', '/', $data['save_path']);
                $data['sha1'] = $info->sha1();
                $data['md5'] = $info->md5();
                $data['create_time'] = time();
                $userInfo = session('user');
                $data['ucenter_id'] = $userInfo['id'];
                $data['type_number'] = "0";//默认为零

                if ($data['ext'] == "jpg" || $data['ext'] == "jpeg" || $data['ext'] == "gif" || $data['ext'] == "psd" || $data['ext'] == "rng" || $data['ext'] == "png") {

                    $data['type_number'] = "1";//类型为图片

                }
                if ($data['ext'] == "docx" || $data['ext'] == "doc") {

                    $data['type_number'] = "2";//类型为word

                }
                if ($data['ext'] == "pdf") {

                    $data['type_number'] = "3";//类型为pdf

                }
                if ($data['ext'] == "ppt") {

                    $data['type_number'] = "4";//类型为ppt

                }

                if ($data['ext'] == "txt") {

                    $data['type_number'] = "5";//类型为记事本

                }
                if ($data['ext'] == "excel" || $data['ext'] == "xlsx") {

                    $data['type_number'] = "6";//类型为excel

                }
                if ($data['ext'] == "rar" || $data['ext'] == "zip") {

                    $data['type_number'] = "7";//类型为压缩文件

                }


                $row = $fileM->save($data);
                $parm['title']  =   "上传文件";

                $parm['project_id'] =   $project_id;
                $parm['from'] =   $userInfo['id'];
                $messageM   = new Message();
                $result =$messageM->addMessage($parm);

                if ($row) {


                    $this->redirect($_SERVER["HTTP_REFERER"]);

                } else {

                    echo $file->getError();
                }


            } else {
                // 上传失败获取错误信息
                echo $file->getError();
            }

        }

    }

//删除文件
    public function deleteFolder()
    {

        $request = Request::instance();
        $list = $request->param();
        $fileM = new \app\index\model\File();
        $a = implode(',', $list['id']);

        $b['id'] = array('in', $a);

        $result = $fileM->deleteFolder($b);

        return $result;


    }

    public function deleteFolder1()
    {

        $request = Request::instance();
        $list = $request->param();
        $fileM = new FileShare();
        $a = implode(',', $list['id']);

        $b['id'] = array('in', $a);

        $result = $fileM->deleteFolder($b);

        return $result;


    }

    //文件重命名
    public function reName()
    {

        $request = Request::instance();
        $list = $request->param();
        $fileM = new \app\index\model\File();

        $result = $fileM->reName($list);

        return $result;

    }

    public function reName1()
    {

        $request = Request::instance();
        $list = $request->param();
        $fileM = new FileShare();

        $result = $fileM->reName($list);

        return $result;

    }

    //新建文件夹
    public function new_folder()
    {


    }

    public function editFolder()
    {


        $fileShare  =   new FileShare();

        $request    =   Request::instance();
        $list       =  $request->param();
        $result =   $fileShare->where($list)->select();
        $this->assign('result',$result);


        return $this->fetch();


    }

    //新建文件夹
    public function addFolder()
    {

        $request = Request::instance();
        $list = $request->param();
        $fileM = new \app\index\model\File();
        if(!isset($list['folder_id'])||$list['folder_id']==null||$list['folder_id']==""){

            $list['folder_id']=0;
        }
        $result = $fileM->addFolder($list);


        return $result;


    }

    public function share()
    {


        $fileShareM =   new FileShare();
        $result =   $fileShareM->select();
        $this->assign('result',$result);
        return $this->fetch();
    }

    public function addFolder1()
    {

      $list['id']   =   0;
        $fileM = new FileShare();
        $result = $fileM->addFolder($list);


        return $result;


    }

    public function upload1()
    {
        $file = request()->file('file');

        //项目的id
        $project_id = input('id');
        $folder_id = input('folder_id');
        dump($folder_id);
        return $folder_id;
        if ($folder_id == "" || $folder_id == null) {
            $folder_id = 0;

        }


        if ($file) {

            // 移动到框架应用根目录/public/uploads/ 目录下
            $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads', '', false);

            if ($info) {
                // 成功上传后 获取上传信息
                $fileM = new FileShare();
                $data['project_id'] = $project_id;
                $data['name'] = $info->getInfo('name');
                $data['mime'] = $info->getInfo('type');
                $data['size'] = $info->getInfo('size');
                $data['folder_id'] = $folder_id;
                $data['ext'] = $info->getExtension();
                $data['save_name'] = $info->getFilename();
//                $data['save_name']  =   $info->getInfo('name');
                $data['save_path'] = $info->getSaveName();
//                $path = dirname(dirname(dirname(dirname(__FILE__)))) . '/public';;
//                $path = str_replace('\\', '/', $path);
//                $data['save_path'] = str_replace($path, '', $data['save_path']);
                $data['save_path'] = '/public/uploads/' . $data['save_path'];
                $data['save_path'] = str_replace('\\', '/', $data['save_path']);
                $data['sha1'] = $info->sha1();
                $data['md5'] = $info->md5();
                $data['create_time'] = time();
                $userInfo = session('user');
                $data['ucenter_id'] = $userInfo['id'];
                $data['type_number'] = "0";//默认为零

                if ($data['ext'] == "jpg" || $data['ext'] == "jpeg" || $data['ext'] == "gif" || $data['ext'] == "psd" || $data['ext'] == "rng" || $data['ext'] == "png") {

                    $data['type_number'] = "1";//类型为图片

                }
                if ($data['ext'] == "docx" || $data['ext'] == "doc") {

                    $data['type_number'] = "2";//类型为word

                }
                if ($data['ext'] == "pdf") {

                    $data['type_number'] = "3";//类型为pdf

                }
                if ($data['ext'] == "ppt") {

                    $data['type_number'] = "4";//类型为ppt

                }

                if ($data['ext'] == "txt") {

                    $data['type_number'] = "5";//类型为记事本

                }
                if ($data['ext'] == "excel" || $data['ext'] == "xlsx") {

                    $data['type_number'] = "6";//类型为excel

                }

                if ($data['ext'] == "rar" || $data['ext'] == "zip") {

                    $data['type_number'] = "7";//类型为压缩文件

                }

                $row = $fileM->save($data);


                if ($row) {

                    $this->redirect($_SERVER["HTTP_REFERER"]);

                } else {

                    echo $file->getError();
                }


            } else {
                // 上传失败获取错误信息
                echo $file->getError();
            }

        }
    }


}