<?php
/**
 * Created by 高远
 * Date: 2016/10/21
 * Time: 8:53
 */

namespace app\index\controller;


use app\index\model\ActionLog;
use app\index\model\AuthGroup;
use app\index\model\AuthGroupUser;
use app\index\model\Category;
use app\index\model\Company;

use app\index\model\Employee;
use app\index\model\Event;
use app\index\model\File;
use app\index\model\Investment;
use app\index\model\Menu;
use app\index\model\Message;
use app\index\model\Priority;
use app\index\model\ProjectStage;
use app\index\model\Province;


use app\index\model\Ucenter;
use think\Collection;
use think\db\Query;

use think\Controller;
use think\Paginator;
use think\Request;
use think\Session;

class Project extends Base
{

    public function _initialize()
    {


        parent::_initialize(); // TODO: Change the autogenerated stub


    }

    /**
     * @return mixed
     */
    public function index()
    {


        $userInfo = session('user');

        $user_data['user_id'] = $userInfo['id'];
        $authGroupM = new  AuthGroup();
        $authGroupUserM = new AuthGroupUser();
        $auth_result = $authGroupUserM->where($user_data)->find();
        $auth_group = $auth_result['group_id'];

        $auth_result_data['id'] = $auth_result['group_id'];
        $auth_group_result = $authGroupM->where($auth_result_data)->find();

        $auth_group_all = $authGroupM->select();

        $number = count($auth_group_all);

        $number_result = $number - $auth_group_result['order'];


        $data_result1 = $auth_result['underling'];


        $auth_result['underling'] = explode(',', $auth_result['underling']);

        $data_result = $auth_result['underling'];
        $delete_data['id'] = $userInfo['id'];
        //去除与本次用户相同的id

        $key = array_search($data_result, $delete_data);
        array_splice($data_result, $key, 1);

        $data_fin = [];
        for ($k = 0; $k < $number_result; $k++) {

            foreach ($data_result as $i => $v) {
                $map['user_id'] = $v;


                $auth_result_fin = $authGroupUserM->where($map)->find();

                $data_result1 = $data_result1 . "," . $auth_result_fin['underling'];


                $data_fin[$i] = $data_result = $auth_result_fin['underling'];

                $data_fin[$i] = explode(',', $data_fin[$i]);

                if ($data_fin[$i] != null) {
                    $key = array_search($data_fin[$i], $map);
                    array_splice($data_fin[$i], $key, 1);
                }
                $data_fin[$i] = implode(',', $data_fin[$i]);
            }
            $data_fin = array_unique($data_fin);
            $data_fin = array_filter($data_fin);
            $data_result = $data_fin;
        }

        $data_result1 = explode(',', $data_result1);
        $data_result1 = array_unique($data_result1);
        $data_result1 = array_filter($data_result1);

        $data_result1 = implode(',', $data_result1);

        $auth_shaixuan['p.ucenter_id'] = array('in', $data_result1);

        /**
         * 项目更新通知
         */

        $message_action['to'] =  $userInfo['id'];


        $message_action['stage_id'] =  array('neq', 0);

        $messageM   =  new  Message();

        $message_stage_result  =   $messageM->getlist($message_action);

        unset($message_action['stage_id']);
        $message_action['stage_id'] =  array('eq', 0);
            $message_project_result  =   $messageM->getlist1($message_action);



        $this->assign('messagestageLog',$message_stage_result);
        $this->assign('messageproLog',$message_project_result);


        //调用项目
        //  $this->getProject();
        $project = new     \app\index\model\Project();


        //从前台接受参数
        $data['category'] = $category = input('category');

        $data['stage_id'] = $stage_id = input('stage_id');
        $data['charge_id'] = $charge_id = input('charge_id');


        //从前台获得判断是否点击的参数
        $messageJudge   =   input('stage_judge');

        //假如有参数，说明点击，则更该提示状态
        if($messageJudge==1){

            $messageM    = new Message();
            $messageWhere['to'] =   $userInfo['id'];
            $messageWhere['stage_id']   =   input('stage_id');
            $messageM->clickAlerday($messageWhere);

        }


        //跟进人
        if ($charge_id != null && $charge_id != 0) {
            $where5['p.ucenter_id'] = $charge_id;
            $this->assign('charge_id', $charge_id);
        } else {
            $charge_id = 0;
            $this->assign('charge_id', $charge_id);
        }


        //行业分类
        if ($category != null && $category != 0) {
            $where4['p.category_id'] = $where['category_id'] = $category;
            $this->assign('category_id', $where['category_id']);
        } else {
            $data['category'] = 0;
            $this->assign('category_id', $data['category']);
        }

        //项目阶段

        if ($stage_id != null) {
            session('project_stage_id', $stage_id);
            $project_stage_id ['id'] = $stage_id;
            $where4['p.stage_id'] = $data['stage_id'] = $where['stage_id'] = $stage_id;

        } else {

            $projeceStageM = new ProjectStage();
            $result_stage = $projeceStageM->getMax();

            $where4['p.stage_id'] = $data['stage_id'] = $where['stage_id'] = $result_stage;
            session('project_stage_id', $result_stage);
            $project_stage_id ['id'] = $result_stage;

        }


        $this->assign('project_stage_id', $project_stage_id);

        //刚开始的时候刚进入界面全部为零，就显示全部
        if ($category == 0) {

            if ($auth_group == 1 || $auth_group == 2) {


                if ($charge_id == "0") {

                    $result = $project
                        ->alias('p')
                        ->where("p.stage_id=" . $data['stage_id'])
                        ->where("p.status=1")
                        ->order('p.time1 desc')
                        ->field('p.valuation,p.id,p.name,p.create_time,p.brief,c.name cname,p.time1,p.time2,p.category_name,p.company_name,p.ucenter_id,u.user_name ename,p.update_time,p.investment_stage,pr.id pid,pr.name stage_name,p.mobile')
                        ->join('project_stage pr', 'pr.id=p.stage_id')
                        ->join('ucenter u', 'u.id=p.ucenter_id')
                        ->join('category c', 'c.id=p.category_id')
                        ->paginate(10);

                } else {
                    $result = $project
                        ->alias('p')
                        ->where("p.stage_id=" . $data['stage_id'])
                        ->where("p.status=1")
                        ->where($where5)
                        ->order('p.time1 desc')
                        ->field('p.valuation,p.id,p.name,p.create_time,p.brief,c.name cname,p.time1,p.time2,p.category_name,p.company_name,p.ucenter_id,u.user_name ename,p.update_time,p.investment_stage,pr.id pid,pr.name stage_name,p.mobile')
                        ->join('project_stage pr', 'pr.id=p.stage_id')
                        ->join('ucenter u', 'u.id=p.ucenter_id')
                        ->join('category c', 'c.id=p.category_id')
                        ->paginate(10);


                }


            } else {

                if ($charge_id == "0") {


                    $result = $project
                        ->alias('p')
                        ->where("p.stage_id=" . $data['stage_id'])
                        ->where("p.status=1")
                        ->where($auth_shaixuan)
                        ->order('p.time1 desc')
                        ->field('p.valuation,p.id,p.name,p.brief,p.create_time,c.name cname,p.time1,p.time2,p.category_name,p.company_name,p.ucenter_id,u.user_name ename,p.update_time,p.investment_stage,pr.id pid,pr.name stage_name,p.mobile')
                        ->join('project_stage pr', 'pr.id=p.stage_id')
                        ->join('ucenter u', 'u.id=p.ucenter_id')
                        ->join('category c', 'c.id=p.category_id')
                        ->paginate(10);
                } else {


                    $result = $project
                        ->alias('p')
                        ->where("p.stage_id=" . $data['stage_id'])
                        ->where("p.status=1")
                        ->where($where5)
                        ->where($auth_shaixuan)
                        ->order('p.time1 desc')
                        ->field('p.valuation,p.id,p.name,p.brief,p.create_time,c.name cname,p.time1,p.time2,p.category_name,p.company_name,p.ucenter_id,u.user_name ename,p.update_time,p.investment_stage,pr.id pid,pr.name stage_name,p.mobile')
                        ->join('project_stage pr', 'pr.id=p.stage_id')
                        ->join('ucenter u', 'u.id=p.ucenter_id')
                        ->join('category c', 'c.id=p.category_id')
                        ->paginate(10);

                }


            }

        } else {
            if ($auth_group == 1 || $auth_group == 2) {

                if ($charge_id == "0") {


                    $result = $project
                        ->alias('p')
                        ->where($where4)
                        ->where("p.status=1")
                        ->order('p.time1 desc')
                        ->field('p.valuation,p.id,p.name,p.ucenter_id,p.create_time,c.name cname,p.time1,p.time2,p.brief,p.category_name,p.city,u.user_name ename,p.update_time,p.investment_stage,pr.id pid,pr.name stage_name,p.mobile')
                        ->join('project_stage pr', 'pr.id=p.stage_id')
                        ->join('category c', 'c.id=p.category_id')
                        ->join('ucenter u', 'u.id=p.ucenter_id')
                        ->paginate(10);
                } else {

                    $result = $project
                        ->alias('p')
                        ->where($where5)
                        ->where($where4)
                        ->where("p.status=1")
                        ->order('p.time1 desc')
                        ->field('p.valuation,p.id,p.name,p.ucenter_id,p.create_time,c.name cname,p.time1,p.time2,p.brief,p.category_name,p.city,u.user_name ename,p.update_time,p.investment_stage,pr.id pid,pr.name stage_name,p.mobile')
                        ->join('project_stage pr', 'pr.id=p.stage_id')
                        ->join('category c', 'c.id=p.category_id')
                        ->join('ucenter u', 'u.id=p.ucenter_id')
                        ->paginate(10);

                }


            } else {

                if ($charge_id == "0") {

                    $result = $project
                        ->alias('p')
                        ->where($where4)
                        ->where("p.status=1")
                        ->where($auth_shaixuan)
                        ->order('p.time1 desc')
                        ->field('p.valuation,p.id,p.name,p.ucenter_id,p.create_time,c.name cname,p.time1,p.time2,p.brief,p.category_name,u.user_name ename,p.city,p.update_time,p.investment_stage,pr.id pid,pr.name stage_name,p.mobile')
                        ->join('category c', 'c.id=p.category_id')
                        ->join('project_stage pr', 'pr.id=p.stage_id')
                        ->join('ucenter u', 'u.id=p.ucenter_id')
                        ->paginate(10);

                } else {
                    $result = $project
                        ->alias('p')
                        ->where($where4)
                        ->where("p.status=1")
                        ->where($where5)
                        ->where($auth_shaixuan)
                        ->order('p.time1 desc')
                        ->field('p.valuation,p.id,p.name,p.ucenter_id,p.create_time,c.name cname,p.time1,p.time2,p.brief,p.category_name,u.user_name ename,p.city,p.update_time,p.investment_stage,pr.id pid,pr.name stage_name,p.mobile')
                        ->join('category c', 'c.id=p.category_id')
                        ->join('project_stage pr', 'pr.id=p.stage_id')
                        ->join('ucenter u', 'u.id=p.ucenter_id')
                        ->paginate(10);


                }


            }


        }


        $result_item = $result->all();

        if ($result_item != null && !empty($result_item)) {


            foreach ($result as $k => $v) {


                $charge[$k]['charge_user'] = $v['ename'];
                $charge[$k]['ucenter_id'] = $v['ucenter_id'];

            }


            //二维数组去重
            $temp = $this->unique($charge);
            $charge_issert = 1;

            $this->assign('charge', $temp);

        } else {

            $charge_issert = 0;
        }


        $this->assign('charge_issert', $charge_issert);
        $this->assign('data', $data);


        $this->assign('result', $result);


        return $this->fetch();

    }


    //ajax新建项目
    public function add()
    {
        $request = Request::instance();
        $list = $request->param();


        $categoryM = new Category();
        $projectM = new     \app\index\model\Project();

        $list['time1'] = strtotime($list['time1']);
        if($list['time1']==null||$list['time1']==""){
            $list['time1']=time();
        }

        $list['time2'] = strtotime($list['time2']);
        if($list['time2']==null||$list['time2']==""){
            $list['time2']=time();
        }
        dump($list['time1']);
        return $list['time2'];
        $list['category_name'] = $categoryM->getName($list['category_id']);

        $data = $projectM->savaAll($list);



        return 1;


    }

    public function getUser()
    {
        $userInfo = session('user');

        $this->assign('userInfo', $userInfo);

    }


    public function test()
    {

        $menu = new Menu();
        $a = $menu->tree();


    }

    //新建项目页面
    public function newProject()
    {


        return $this->fetch();
    }


    //编辑项目页显示
    public function edit()
    {

        $employeeM = new  Employee();
        $request = Request::instance();
        $list = $request->param();
        $userInfo=session('user');
        $message_action['to'] =  $userInfo['id'];


        $message_action['stage_id'] =  array('neq', 0);

        $messageM   =  new  Message();

        $message_stage_result  =   $messageM->getlist($message_action);

        unset($message_action['stage_id']);
        $message_action['stage_id'] =  array('eq', 0);
        $message_project_result  =   $messageM->getlist1($message_action);



        $this->assign('messagestageLog',$message_stage_result);
        $this->assign('messageproLog',$message_project_result);

        $messageJudge   =   $list['message_judge'];
        if($messageJudge==1){

            $messageWhere['project_id'] =   $list['id'];
            $userInfo   =   session('user');
            $messageWhere['to'] =   $userInfo['id'];
            $messageM    = new  Message();
            $messageM->clickAlerday($messageWhere);
        }



        unset($list['message_judge']);
        $fileM = new File();
        $projectM = new \app\index\model\Project();
        $ucenterM = new Ucenter();
        $eventM = new Event();

        $project_stage_id = $list['stage_id'];


        $this->assign('project_stage_id', $project_stage_id);
        unset($list['stage_id']);


        //查询事件详情

        $ev_result = $eventM->getAll($list);

        foreach ($ev_result as $key => $va) {


            $ev_result[$key]['event_time'] = date('Y-m-d H:i', $va['event_time']);


        }
        //查询文件
        $file_result = $fileM->getAll($list);


        foreach ($ev_result as $key => $value) {

            $ev_result[$key]['employee_name'] = $ucenterM->getName($value['ucenter_id']);


        }


        //查询项目详情
        $pr_result = $projectM->getWhere($list);
        $where = $pr_result['ucenter_id'];
        $pr_result['ucenter_name'] = $ucenterM->getName($where);
        $this->assign('file_result', $file_result);
        $this->assign('ev_result', $ev_result);
        $this->assign('pr_result', $pr_result);

        return $this->fetch();
    }

    //ajax修改项目
    public function editProject()
    {

        $projectM = new \app\index\model\Project();
        $request = Request::instance();
        $list = $request->param();

        $result = $projectM->editProject($list);


        return $result;


    }

    //删除项目  更改status
    public function deleteProject()
    {

        $projectM = new    \app\index\model\Project();
        $request = Request::instance();
        $list = $request->param();

        $result = $projectM->deledtProject($list);

        return $result;


    }

    public function editFolder()
    {

        $employeeM = new  Employee();
        $request = Request::instance();
        $list = $request->param();
        $fileM = new File();
        $projectM = new \app\index\model\Project();
        $eventM = new Event();


        $list1['id'] = $list['project_id'];
        $list2['folder_id'] = $list['id'];
        $this->assign('folder_id', $list2['folder_id']);


        $this->assign('project_id', $list['project_id']);


        //查询文件夹内文件
        $folder_detail = $fileM->getFolder($list);

        $this->assign('folder_detail', $folder_detail);


        //查询项目详情
        $pr_result = $projectM->getWhere($list1);

        $this->assign('pr_result', $pr_result);
        $this->assign('list', $list);

        return $this->fetch();

    }

    //用户权限
    public function menu()
    {


    }
}