<?php
/**
 * Created by 高远
 * Date: 2016/11/17
 * Time: 15:28
 */

namespace app\index\controller;


use think\Request;

class ProjectStage extends  Base
{
    public  function _initialize()
    {


        parent::_initialize(); // TODO: Change the autogenerated stub

    }
    //新建项目库
    public  function  add(){

        $request    =    Request::instance();
        $projectStageM  =  new \app\index\model\ProjectStage();
        $list       =   $request->param();
        $result     =   $projectStageM->add($list);


       return $result;

    }

    //删除项目库
    public  function delete(){
        $request    =    Request::instance();
        $projectStageM  =  new \app\index\model\ProjectStage();
        $list       =   $request->param();
        $result     =   $projectStageM->delete_stage($list);


       return $result;

    }
    //编辑项目库名称
    public  function edit(){
        $request    =    Request::instance();
        $projectStageM  =  new \app\index\model\ProjectStage();
        $list       =   $request->param();
        $result     =   $projectStageM->edit($list);


        return $result;

    }

}